Add instructions to README, and update link on Get Started page
okTurtles/groupincome.org pull request #129
Opened 2024-07-21 17:19 UTC by blaesy

Added instructions in README with an anchor (#).
Added redirect from Get started page to the anchor in README in the original repo.

Issue #122

2024-07-21 17:20 UTC, blaesy commented on README.md
> +This theme is based off of the lovely [Bear Blog](https://github.com/HermanMartinus/bearblog/).
No changes, Git marks as a change - not relevant.

2024-07-21 17:24 UTC, taoeffect requested changes
Awesome, thanks @blaesy!

Left a review :)

2024-07-21 17:24 UTC, taoeffect commented on README.md
> +The archive file contains a dist/ folder that needs to be placed into a copy of this cloned repo. Then you can serve it using grunt serve. On a production site, you should to use these environment va
Ahh, I see... what happened, sorry for not being clear in the issue - but this section should be added to the README in the group-income repo, not the groupincome.org repo. Can you send in a PR there?

For this PR we just need the change below to link to the group-income repo.

(Also, can you add an empty line after the heading too?)

2024-07-21 17:24 UTC, taoeffect commented on src/pages/get-started.astro
> +        <a href="https://github.com/okTurtles/groupincome.org#-instructions-on-how-to-run-your-own-server" class="link server-link" target="_blank">
Please update this to point to the `group-income` repo's README, and double-check that the hash is correct as I'd be surprised if it started with a `-`...

2024-08-29 03:12 UTC, taoeffect commented
Stale

2024-08-29 03:12 UTC, closed without merging